version: '2'

build:
  context: .
  args:
    - KODEXPLORER_VERSION=4.51.02

services:
  kodexplorer:
    image: dudw/kodexplorer
    restart: always
    ports:
      - '8006:80'
    volumes:
      - '/srv/docker/kodexplorer-data:/var/www/html'
